name: test

on:
  schedule:
    - cron: '0 11 * * 1'   # Monday
    - cron: '50 18 * * 2'  # Tuesday
    - cron: '50 02 * * 3'  # Wednesday
    - cron: '0 11 * * 4'   # Thursday
    - cron: '50 18 * * 5'  # Friday
    - cron: '50 02 * * 6'  # Saturday
    - cron: '0 11 * * 0'   # Sunday
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
   
    - name: app
      run: |
        chmod +x entrypoint.sh

    - name: app run
      run: |
        bash entrypoint.sh
